line_length:
  warning: 250
  error: 1000

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - CurrencyConverter/SwiftGen/

# rule identifiers to exclude from running
disabled_rules: 
  - vertical_whitespace	