name: CurrencyConverter 
options:
  bundleIdPrefix: com.artem.krachulov
  deploymentTarget:
    iOS: "14.0"

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit.git
    version: 5.0.1

  CombineMoya:
    url: https://github.com/Moya/Moya.git
    version: 15.0.0

targets:
  CurrencyConverter:
    type: application
    platform: iOS
    deploymentTarget: "14.0"

    dependencies:
      - package: SnapKit
      - package: CombineMoya

    sources:
      - path: CurrencyConverter

    postCompileScripts:
      - name: ⚠️ SwiftLint
        runOnlyWhenInstalling: false
        shell: /bin/sh
        script: |
          if command -v swiftlint >/dev/null 2>&1
            then
              swiftlint
            else
              echo "warning: `swiftlint` command not found - See https://github.com/realm/SwiftLint#installation for installation instructions."
          fi
        basedOnDependencyAnalysis: false
      - name: 🛠 SwiftGen
        runOnlyWhenInstalling: false
        shell: /bin/sh
        script: |
          if which swiftgen >/dev/null; then
            swiftgen
          else
            echo "warning: SwiftGen not installed, download it from https://github.com/SwiftGen/SwiftGen"
          fi
          
  CurrencyConverterTests:
    type: bundle.unit-test
    platform: iOS

    info:
      path: CurrencyConverterTests/Info.plist

    sources:
      - path: CurrencyConverterTests

    dependencies:
      - target: CurrencyConverter
      
